target 'SearchMediaSampleByRxSwift' do
  use_frameworks!

  # 1. アーキテクチャの基盤ライブラリ
  pod 'RxSwift'
  pod 'RxCocoa'
 
  # 2. 非同期処理や画像キャッシュ等の用途で利用するライブラリ
  pod 'APIKit'
  pod 'Nuke'

  # 3. UI関連処理で利用するライブラリ
  pod 'DynamicButton'
  pod 'SwiftyAttributes'
  pod 'BetterSegmentedControl'
  pod 'PKHUD'
  pod 'AnimatedCollectionViewLayout'
  pod 'Toast-Swift'
  pod 'TagListView'
  pod 'BouncyLayout'
  pod 'SkeletonView'
  pod 'Parchment'
end
