# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LayeredArchitectureAndUiExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LayeredArchitectureAndUiExample

  # 1. アーキテクチャに関するライブラリ
  pod 'RxSwift', '6.0.0-rc.1'
  pod 'RxCocoa', '6.0.0-rc.1'
  pod 'RealmSwift'
  pod 'KeychainAccess'
  pod 'Kingfisher'

  # 2. UI実装に関するライブラリ
  pod 'YNDropDownMenu'
  pod 'BouncyLayout'
  pod 'Panels'
  pod 'ParallaxHeader', '~> 3.0.0'
end
