# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LayeredArchitectureAndUiExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LayeredArchitectureAndUiExample

  target 'LayeredArchitectureAndUiExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LayeredArchitectureAndUiExampleUITests' do
    # Pods for testing
  end

end
