# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FavoriteSpotSampleByReSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FavoriteSpotSampleByReSwift

  target 'FavoriteSpotSampleByReSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FavoriteSpotSampleByReSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
