# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FavoriteSpotSampleByReSwift' do
  use_frameworks!

  # 1. アーキテクチャの基盤ライブラリ
  pod 'ReSwift'

  # 2. 非同期処理や画像キャッシュ等の用途で利用するライブラリ
  pod 'Alamofire'
  pod 'PromiseKit'
  pod 'Kingfisher'
  pod 'RealmSwift'

  # 3. UI関連処理で利用するライブラリ
  pod 'PanModal'
  pod 'SwipeCellKit'
  pod 'Gemini'
  pod 'GrowingTextView'
  pod 'NVActivityIndicatorView'
  pod 'CalculateCalendarLogic'
end
