# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'RxSwiftAndUiExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftAndUiExample
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftyUserDefaults', '~> 5.0'
  pod 'GrowingTextView', '0.7.2'
  pod 'BulletinBoard'
  pod 'DropDown'
  pod 'GRDB.swift'

  target 'RxSwiftAndUiExampleTests' do
    inherit! :search_paths
    pod 'RxBlocking'
    pod 'RxTest'
  end
end
